name: Build Executable and Create Release

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Executable
      run: |
        pip install pyinstaller
        pyinstaller --onefile main.py 

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: main.exe
        path: ./dist/main.exe

    - name: Download Executable Artifact
      uses: actions/download-artifact@v2
      with:
        name: main.exe
        path: ./dist/

    - name: Create Release
      id: create_release
      uses: gh-actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: Auto-generated release from ${{ github.sha }}

    - name: Upload Executable to Release
      uses: gh-actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/main.exe
        asset_name: main.exe
        asset_content_type: application/octet-stream
