name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Create Executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile main.py 

      - name: Get Executable Path
        id: get-path
        run: |
          echo "::set-output name=path::$(find . -name ./dist/main.exe)"
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Update Release
        uses: gh-actions/gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          asset_path: ${{ steps.get-path.outputs.path }}
          asset_name: your-executable-name
          asset_content_type: application/octet-stream