name: Build Executable

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Executable
      run: |
        pip install pyinstaller
        pyinstaller --onefile your_script.py  # Replace 'your_script.py' with the name of your main Python script

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: your-executable
        path: ./dist/your_script  # Replace 'your_script' with the name of your main Python script without the '.py' extension
